### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by nittygritty94** [Rahien/aoe2-build-orders#3]
Hi

Sound is not working on webview browser of Anroid?

Any idea?

I m looking forward to your answer.

**Comment by Rahien** [comment]
Hi!

Thanks for reaching out. Could you provide me with the version of webview that you are using? According to MDN, the API that I'm using should work from 4.4.3 onward: https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis#Browser_compatibility

Cheers!

**Comment by Rahien** [comment]
So I did some more looking around in the mean time and unfortunately, while the base library is indeed supported in webview, it seems that the utterance object used to create text to speech effects is not: https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance

There is a bug open here: https://bugs.chromium.org/p/chromium/issues/detail?id=487255

Unfortunately, the last dev activity on this bug dates back to almost a year ago...

I'll have to close this as I can't help you until this bug is fixed...
